### ISSUE TITLE
Package not in stackage

### ISSUE THREAD

**Issue by ysangkok** [jonpetterbergman/timezone-olson-th#5]
Hello again Petter Bergman.

We are using your package and it is working great for us. I noticed that it is not on Stackage though. I would happily add it myself, but [the instructions](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package) say that it is better if the maintainer adds it. So I thought I'd ask here first. If you don't want to, of course it is totally fine and I could attempt adding it under my own name.

Many regards,
Janus

**Comment by jonpetterbergman** [comment]
Hi,

I don't use stackage myself and have no idea how it works, so I don't want
to add it there. (my own applications that depend on timezone-olson-th are
so old they predate stackage).

I'm open to different solutions here: You could add it to stackage, or you
could become the maintainer and add it. Or the maintainer of
timezone-series/olson could take over this package (I'm assuming those
packages are on stackage), perhaps that would be the best long term option,
given that the packages are so closely linked.

/PB

Den mån 24 jan. 2022 kl 20:36 skrev Janus Troelsen ***@***.***

**Comment by ysangkok** [comment]
Thank you Petter! I added it as part of
* https://github.com/commercialhaskell/stackage/pull/6414
